version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the docker image
          command: docker build -t this .
      - run:
          name: Validate the container using docker run
          command: docker run this node -v
